name: Gradle Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11, 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
          java-package: jdk
          architecture: x64
      - run: ./gradlew build
      - uses: codecov/codecov-action@v2
        if: matrix.jdk == 11
        with:
          directory: ./build/reports/jacoco
