name: Build Gradle

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11, 15 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
          java-package: jdk
          architecture: x64
      - uses: codecov/codecov-action@v1
        if: matrix.jdk == 11
        with:
          directory: ./build/reports/jacoco
      - run: ./gradlew build
