name: Build Gradle

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '8', '9', '10', '11', '12', '13', '14', '15' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          architecture: x64
      - run: ./gradlew build
