name: Build Gradle

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '8', '11', '15' ]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          architecture: x64
      - uses: codecov/codecov-action@v1
      - run: ./gradlew build
